### ISSUE TITLE
The machine readable json contains wrong base_urls.

### ISSUE THREAD

**Issue by GreyBjorn** [Materials-Consortia/providers#75]
I developed a GUI to browse Optimade. 
I want the GUI to be completely dynamic.
So the first RESTapi call goes to https://providers.optimade.org/v1/links to retrieve the various provider URLs.
The problem is that only 3 provider have correct base_url parameters.  (Necroptimade, Xtals and Materials Cloud)

for example
Theoretical Crystallography Open Database
has:
"base_url": "http://providers.optimade.org/index-metadbs/tcod"
while I thought that the real base URL should be:
"https://www.crystallography.net/tcod/optimade".

Am I wrong or some URL are misleading?

**Comment by CasperWA** [comment]
These base URLs lead to the index meta-database, which lists all databases a database provider has/provides. For more information about the index meta-database see [this section](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#index-meta-database) of the OPTIMADE specification.

In short, it's a limited OPTIMADE implementation that only supplies the `/info` and `/links` endpoints, where the `/links` endpoints is the one listing all provided databases.

**Comment by ml-evs** [comment]
Just to add that the URLs that look "incorrect", e.g. `http://providers.optimade.org/index-metadbs/tcod` are due to the static index meta-database hosting service that this repository serves. If a provider only hosts one database (or a semi-constant number of databases), then they can serve their index meta-database here without having to run a web server.

You should find that all of the base URL links are valid once you append `/v1/links` to them. We are working on making the 404 pages more informative for the static index meta-database service (I have just made an issue to track this #76).

**Comment by ml-evs** [comment]
> I developed a GUI to browse Optimade.

Forgot to say, this sounds exciting! Please get in touch if you want to advertise it on the optimade.org website. We have monthly meetings coming up too if you want to get involved with the OPTIMADE developers: https://www.optimade.org/#get-involved

**Comment by GreyBjorn** [comment]
I'm going to publish the GUI asap. 
Ok thanks a lot for the quick response. I now have all data appending "/v1/links" as you guys said.
